### ISSUE TITLE
스터디 운영 계획

### ISSUE THREAD

**Issue by xonic789** [xonic789/coding-test#1]
## 스터디 목적
- 코딩 테스트를 위한 꾸준한 문제 풀이
- 꾸준한 문제 풀이에 초점을 맞춘다.
- 쿠버네티스 과정내 **코딩테스트 고득점 획득** 및 **기업 코딩테스트 최저 솔** 기준을 목표로 한다.

## 스터디 팀원
- [heyhmin](https://github.com/heyhmin) : `C++`
- [hwangjeunghwan](https://github.com/hwangjeunghwan) : `JAVA`
- [JJY2021](https://github.com/JJY2021) : `C, C++`
- [normal-beom](https://github.com/normal-beom) : `Python`
- [xonic789](https://github.com/xonic789) : `JAVA`

## 스터디 방법
- 매주 화요일마다 각자 한 문제씩 골라 링크를 카카오 워크에 남긴다.
- 선착순으로 **3문제까지 끊어 풀고** 나머지 **2문제는 선택 문제**이며, 풀어도 되고 풀지 않아도 된다.
  - 백준, 프로그래머스 매주 번갈아 가며 풀며 백준은 문제집 (단기간 성장 문제 좋은거 같아요), 프로그래머스는 단계별 문제를 추린다.
- 매주 화요일(수요일)까지 레포지토리로 PR을 날린다.
- 각 PR마다 approve 3건이 있어야 merge가 가능하다.
- approve는 코드 리뷰 코멘트 한 건당 한 번 누를 수 있다.

## 코드 리뷰 방법
1. 코드에 대한 질문
  - 예를들어
    - 왜 `DFS`말고 `BFS`를 사용했는지,
    - 왜 `Stack` 말고 `Deque`를 사용했는지 등
2. 시간 복잡도에 대한 리팩토링
3. 의견..

## 파일 컨벤션

![image](https://user-images.githubusercontent.com/64122884/140010279-df9d85b5-ed7a-4982-a45c-aef364a471ed.png)
![image](https://user-images.githubusercontent.com/64122884/140010299-b9f19598-2842-4dc2-8420-15b7a71ff4f4.png)
- 백준의 경우 `BOJ_{문제번호}_{문제제목}`
- 프로그래머스의 경우 `PRO_{문제번호}_{문제제목}`
- 예)
![image](https://user-images.githubusercontent.com/64122884/140012538-301e5b17-3e7f-4486-accc-d000bc56f9b5.png)

  
## 진행 방법
- 본인의 이름에 해당하는 디렉토리를 IDE에서 workspace로 잡는다.
- 소스코드 제외 필요 없는 모든 파일은 ignore 처리한다. (이건 제가 해도 돼요)

## 커밋 컨벤션
- 1 문제당 1 커밋을 원칙으로 한다.
- 커밋 제목 : github nickname !: 문제 이름 
  - 예) xonic !: BOJ 12865번 평범한 배낭
- 커밋 description : 간단한 풀이
  - 예) 해당 문제는 알고리즘을 쓰지 않고 구현.
  - 예) BFS 사용하여 구현

**Comment by heyhmin** [comment]
문제집(백준 - 단기간 성장 등)을 선택하여 위부터 5개(1 ~ 5) 중 3개를 선택하여 문제를 푼다. 다음주는 그 아래부터 5개(6 ~ 10)를 선택하여 그 중 3개를 푼다.

**Comment by normal-beom** [comment]
**프로그래머스(모든 문제)**
- 난이도 : 1~2(3)
- 언어 : C++, JAVA, Python


1. 위 항목에서 각자 하나씩 선택해서 카카오 워크에 공유한다.
(최대 5개 이하)

2. 투표를 통해 3개를 선정하고, 특정 요일까지 완료 후 주석과 함께 해당 코드를 공유한다.
(깃헙 등)

3. 특정 요일이 되면 시간을 맞춰 리뷰하는 시간을 갖는다.
(같은 언어가 아닌 경우 리뷰의 효과가 있을지 의문입니다. 스터디의 목적이 무엇인지 정하는 게 먼저일 것 같습니다.)

4. 위 과정을 반복한다.
